# This script takes the following arguments-
## An output table generated by inStrain compare, e.g. "FMT.COMPARE"
## A tab-separated text file with a list of scaffold names and corresponding genome names
## An output file name

## load packages and read environmental variables
library(readr)
library(tidyverse)
args = commandArgs(trailingOnly = TRUE)
message(sprintf(args[1L],args[2L]),args[3L])
compare=read_tsv(args[1L])
stb=read_table(args[2L])

### join genome names to inStrain compare table using scaffold names as linker
compare=left_join(compare,stb,by=c("scaffold"="scaffold"))

### subset to comparisons for which ≥25% of the scaffold was covered
compare_perc25=compare[compare$percent_genome_compared>=0.25,]
compare_perc25$genome=compare_perc25$bin

### combine scaffolds from the same genome
compare_perc25$pair=apply(compare_perc25,1,function(x){paste(sort(c(x["name1"],x["name2"])),collapse="/")})
compare_genomewide=aggregate(list(compare_perc25$conANI,compare_perc25$popANI),list(compare_perc25$bin,compare_perc25$pair),function(x){return(1)})
colnames(compare_genomewide)=c("genome","pair","conANI","popANI")

### calculate weighted average consensus ANI and population ANI across all scaffolds
for (pair in unique(compare_perc25$pair)){
	genomes<-unlist(unique(compare_perc25[compare_perc25$pair==pair,"genome"]))
	for (genome in genomes){
		     compare_genomewide[compare_genomewide$genome==genome & compare_genomewide$pair==pair,"conANI"]<-sum(compare_perc25[compare_perc25$pair==pair & compare_perc25$genome==genome,"conANI"]*compare_perc25[compare_perc25$pair==pair & compare_perc25$genome==genome,"length"])/sum(compare_perc25[compare_perc25$pair==pair & compare_perc25$genome==genome,"length"])
		     compare_genomewide[compare_genomewide$genome==genome & compare_genomewide$pair==pair,"popANI"]<-sum(compare_perc25[compare_perc25$pair==pair & compare_perc25$genome==genome,"popANI"]*compare_perc25[compare_perc25$pair==pair & compare_perc25$genome==genome,"length"])/sum(compare_perc25[compare_perc25$pair==pair & compare_perc25$genome==genome,"length"])
  }
}
### write output
write.table(compare_genomewide,args[3L],row.names=F,quote=F)
